# This is a basic workflow to help you get started with Actions

name: "Jobs - Exercise 02"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: "Premier job"
    runs-on: ubuntu-latest
    steps:
    - run: |
        dayOfWeek=$(date +%u)  # calcule le jour de la semaine au format chiffre
        if ($dayOfWeek > 5)
        then
          exit 1
        fi
  job2:
    name: "Deuxième job"
    needs: job1
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "quelquechose s'est mal passé"
  job3:
    name: "Troisième job"
    needs: job2
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Je m'exécute, quoiqu'il arrive"
    
