# This is a basic workflow to help you get started with Actions

name: Matrix - Exercise 01

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        dotnet: [4.2.x, 5.0.x]
        buildMode: [Debug, Release]
    runs-on: window-latest
    steps:
    - name: Récupère le code source
      uses: action/checkout@v2
    - name: Install .NET
      uses: action/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}} # récupération de la variable dotnet de notre matrice
    - name: Restore-dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no restore --configuration ${{env.buildMode}}
      env:
        buildmode: ${{matrix.buildMode}}
