# This is a basic workflow to help you get started with Actions

name: "Triggers - execise 1"

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 19 * * MON-FRI'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
        days-before-stale: 30
        days-before-close: 5
