# This is a basic workflow to help you get started with Actions

name: 'Triggers - Exercice 03'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    paths:
    - '**.yml'
    - '!**/test/**.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Je vérifie les fichiers YAML."
