# This is a basic workflow to help you get started with Actions

name: Variables - Exercise 03

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: echo "${{toJson(github)}}" # ne pas oublier les guillemets
    - name: Nom du workflow
      run: echo ${{github.workflow}}
    - name: URL du profil du owner du repository
      run: echo ${{github.event.repository.owner.html_url}}
    - if: ${{github.event.repository.private == 'false'}}
      name: URL du profile du owner du repository
      run: echo "::warning::Ce rpository est public!"
