# This is a basic workflow to help you get started with Actions

name: Variables - Exercise 01

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR1: "hello"
    steps:
    - run:  |
        echo "Var2=$VAR1" >> $GITHUB_ENV
    - run: echo $VAR2
